export const FBIH_CITIES = [
  // Kantoni
  { name: "Sarajevo", canton: "Kanton Sarajevo", population: 275524 },
  { name: "Mostar", canton: "Hercegovačko-neretvanski", population: 113169 },
  { name: "Tuzla", canton: "Tuzlanski", population: 110979 },
  { name: "Zenica", canton: "Zeničko-dobojski", population: 70553 },
  { name: "Bihać", canton: "Unsko-sanski", population: 57559 },
  { name: "Brčko", canton: "Brčko distrikt", population: 43859 },
  { name: "Goražde", canton: "Bosansko-podrinjski", population: 37562 },
  { name: "Travnik", canton: "Srednjobosanski", population: 57543 },
  { name: "Konjic", canton: "Hercegovačko-neretvanski", population: 14029 },
  { name: "Cazin", canton: "Unsko-sanski", population: 21435 },
  { name: "Vogošća", canton: "Kanton Sarajevo", population: 26381 },
  { name: "Ilidža", canton: "Kanton Sarajevo", population: 29800 },
  { name: "Novo Sarajevo", canton: "Kanton Sarajevo", population: 34562 },
  { name: "Novi Grad", canton: "Kanton Sarajevo", population: 59621 },
  { name: "Stari Grad", canton: "Kanton Sarajevo", population: 36957 },
  { name: "Livno", canton: "Kantonalni centar", population: 34908 },
  { name: "Jajce", canton: "Srednjobosanski", population: 27258 },
  { name: "Bugojno", canton: "Srednjobosanski", population: 31474 },
  { name: "Gračanica", canton: "Tuzlanski", population: 28512 },
  { name: "Gradačac", canton: "Tuzlanski", population: 27683 },
  { name: "Srebrenik", canton: "Tuzlanski", population: 24736 },
  { name: "Bijela", canton: "Tuzlanski", population: 21000 },
  { name: "Kalesija", canton: "Tuzlanski", population: 33053 },
  { name: "Živinice", canton: "Tuzlanski", population: 57765 },
  { name: "Kakanj", canton: "Zeničko-dobojski", population: 38937 },
  { name: "Visoko", canton: "Zeničko-dobojski", population: 21831 },
  { name: "Tešanj", canton: "Zeničko-dobojski", population: 44800 },
  { name: "Zavidovići", canton: "Zeničko-dobojski", population: 39623 },
  { name: "Maglaj", canton: "Zeničko-dobojski", population: 27153 },
  { name: "Bosanska Krupa", canton: "Unsko-sanski", population: 21528 },
  { name: "Velika Kladuša", canton: "Unsko-sanski", population: 44026 },
  { name: "Sanski Most", canton: "Unsko-sanski", population: 47359 },
  { name: "Ključ", canton: "Unsko-sanski", population: 18715 },
  { name: "Bosanski Petrovac", canton: "Unsko-sanski", population: 6783 },
  { name: "Bosansko Grahovo", canton: "Kantonalni centar", population: 3090 },
  { name: "Drvar", canton: "Kantonalni centar", population: 4346 },
  { name: "Glamoč", canton: "Kantonalni centar", population: 3733 },
  { name: "Kupres", canton: "Kantonalni centar", population: 2437 },
  { name: "Jablanica", canton: "Hercegovačko-neretvanski", population: 10054 },
  { name: "Posušje", canton: "Zapadnohercegovački", population: 20400 },
  { name: "Tomislavgrad", canton: "Zapadnohercegovački", population: 33600 },
  { name: "Široki Brijeg", canton: "Zapadnohercegovački", population: 29148 },
  { name: "Grude", canton: "Zapadnohercegovački", population: 16500 },
  { name: "Ljubuški", canton: "Zapadnohercegovački", population: 13000 },
  { name: "Čapljina", canton: "Hercegovačko-neretvanski", population: 21450 },
  { name: "Neum", canton: "Hercegvačko-neretvanski", population: 4653 },
  { name: "Stolac", canton: "Hercegvačko-neretvanski", population: 14410 },
  { name: "Ravno", canton: "Hercegvačko-neretvanski", population: 3329 },
  { name: "Prozor-Rama", canton: "Srednjobosanski", population: 16297 },
  { name: "Donji Vakuf", canton: "Srednjobosanski", population: 14799 },
  { name: "Vitez", canton: "Srednjobosanski", population: 27000 },
  { name: "Busovača", canton: "Srednjobosanski", population: 18500 },
  { name: "Kiseljak", canton: "Srednjobosanski", population: 21000 },
  { name: "Fojnica", canton: "Srednjobosanski", population: 12600 },
  { name: "Breza", canton: "Zeničko-dobojski", population: 14167 },
  { name: "Vareš", canton: "Zeničko-dobojski", population: 8945 },
  { name: "Olovo", canton: "Zeničko-dobojski", population: 10851 },
  { name: "Bosanski Šamac", canton: "Posavski", population: 8323 },
  { name: "Odžak", canton: "Posavski", population: 19993 },
  { name: "Domaljevac-Šamac", canton: "Posavski", population: 5230 },
  { name: "Lukavac", canton: "Tuzlanski", population: 46000 },
  { name: "Banovići", canton: "Tuzlanski", population: 22583 },
].sort((a, b) => a.name.localeCompare(b.name, "hr"));

export const FBIH_CANTONS = [
  "Kanton Sarajevo",
  "Unsko-sanski",
  "Tuzlanski",
  "Zeničko-dobojski",
  "Bosansko-podrinjski",
  "Srednjobosanski",
  "Hercegovačko-neretvanski",
  "Zapadnohercegovački",
  "Kantonalni centar",
  "Posavski",
];

export const FBIH_CANTON_CITIES: Record<string, string[]> = {
  "Kanton Sarajevo": [
    "Sarajevo",
    "Vogošća",
    "Ilidža",
    "Novo Sarajevo",
    "Novi Grad",
    "Stari Grad",
  ],
  "Unsko-sanski": [
    "Bihać",
    "Cazin",
    "Bosanska Krupa",
    "Velika Kladuša",
    "Sanski Most",
    "Ključ",
    "Bosanski Petrovac",
  ],
  "Tuzlanski": [
    "Tuzla",
    "Gračanica",
    "Gradačac",
    "Srebrenik",
    "Kalesija",
    "Živinice",
    "Lukavac",
    "Banovići",
  ],
  "Zeničko-dobojski": [
    "Zenica",
    "Kakanj",
    "Visoko",
    "Tešanj",
    "Zavidovići",
    "Maglaj",
    "Breza",
    "Vareš",
    "Olovo",
  ],
  "Bosansko-podrinjski": ["Goražde"],
  "Srednjobosanski": [
    "Travnik",
    "Jajce",
    "Bugojno",
    "Prozor-Rama",
    "Donji Vakuf",
    "Vitez",
    "Busovača",
    "Kiseljak",
    "Fojnica",
  ],
  "Hercegovačko-neretvanski": [
    "Mostar",
    "Konjic",
    "Jablanica",
    "Čapljina",
    "Neum",
    "Stolac",
    "Ravno",
  ],
  "Zapadnohercegovački": [
    "Posušje",
    "Tomislavgrad",
    "Široki Brijeg",
    "Grude",
    "Ljubuški",
  ],
  "Kantonalni centar": [
    "Livno",
    "Bosansko Grahovo",
    "Drvar",
    "Glamoč",
    "Kupres",
  ],
  "Posavski": ["Bosanski Šamac", "Odžak", "Domaljevac-Šamac"],
};
